[platformio]
default_envs = xxsr69_test

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:xxsr69_test]
board = esp32dev
upload_speed = 57600
upload_flags =
  --before
  no_reset
  --after
  hard_reset
build_flags =
  -D XXSR69_TEST
  -D DISABLE_TFT

[env:lolin_c3_mini]
board = lolin_c3_mini
lib_deps =
  moononournation/GFX Library for Arduino@1.4.7
